-- MySQL Script generated by MySQL Workbench
-- Mon May 16 03:33:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BAETAVERSE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BAETAVERSE` ;

-- -----------------------------------------------------
-- Schema BAETAVERSE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BAETAVERSE` DEFAULT CHARACTER SET utf8 ;
USE `BAETAVERSE` ;

-- -----------------------------------------------------
-- Table `BAETAVERSE`.`OWNER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAETAVERSE`.`OWNER` ;

CREATE TABLE IF NOT EXISTS `BAETAVERSE`.`OWNER` (
  `uuid` VARCHAR(36) NOT NULL DEFAULT (UUID()),
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `IX_U_USER_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAETAVERSE`.`REQUEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAETAVERSE`.`REQUEST` ;

CREATE TABLE IF NOT EXISTS `BAETAVERSE`.`REQUEST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trade_type` VARCHAR(45) NOT NULL,
  `trade_detail` VARCHAR(45) NOT NULL,
  `forwarding_date` DATETIME NOT NULL,
  `departure_country` VARCHAR(45) NOT NULL,
  `departure_detail` VARCHAR(45) NOT NULL,
  `destination_country` VARCHAR(45) NOT NULL,
  `destination_detail` VARCHAR(45) NOT NULL,
  `incoterms` VARCHAR(45) NOT NULL,
  `closing_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `owner_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IX_N_REQUEST_owner_uuid` (`owner_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_QUOTE_REQUEST_OWNER`
    FOREIGN KEY (`owner_uuid`)
    REFERENCES `BAETAVERSE`.`OWNER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAETAVERSE`.`FORWARDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAETAVERSE`.`FORWARDER` ;

CREATE TABLE IF NOT EXISTS `BAETAVERSE`.`FORWARDER` (
  `uuid` VARCHAR(36) NOT NULL DEFAULT '(UUID())',
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `coporation_name` VARCHAR(45) NOT NULL,
  `coporation_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `IX_U_FORWARDER_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAETAVERSE`.`GOODS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAETAVERSE`.`GOODS` ;

CREATE TABLE IF NOT EXISTS `BAETAVERSE`.`GOODS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `weight` INT UNSIGNED NOT NULL,
  `standard_unit` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `request_id` INT NOT NULL,
  UNIQUE INDEX `IX_U_GOODS_id` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `request_id`),
  INDEX `IX_N_GOODS_request_id` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_GOODS_QUOTE_REQUEST1`
    FOREIGN KEY (`request_id`)
    REFERENCES `BAETAVERSE`.`REQUEST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAETAVERSE`.`QUOTATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAETAVERSE`.`QUOTATION` ;

CREATE TABLE IF NOT EXISTS `BAETAVERSE`.`QUOTATION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ocean_freight_price` INT UNSIGNED NOT NULL,
  `inland_freight_price` INT NOT NULL,
  `total_price` INT UNSIGNED NOT NULL,
  `estimated_time` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `forwarder_uuid` VARCHAR(36) NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IX_N_QUOTATION_forwarder_uuid` (`forwarder_uuid` ASC) VISIBLE,
  INDEX `IX_N_QUOTATION_request_id` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_QUOTATION_FORWARDER1`
    FOREIGN KEY (`forwarder_uuid`)
    REFERENCES `BAETAVERSE`.`FORWARDER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QUOTATION_QUOTE_REQUEST1`
    FOREIGN KEY (`request_id`)
    REFERENCES `BAETAVERSE`.`REQUEST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BAETAVERSE`.`REVIEW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BAETAVERSE`.`REVIEW` ;

CREATE TABLE IF NOT EXISTS `BAETAVERSE`.`REVIEW` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `score` TINYINT UNSIGNED NOT NULL,
  `message` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `owner_uuid` VARCHAR(36) NOT NULL,
  `forwarder_uuid` VARCHAR(36) NOT NULL,
  `request_id` INT NOT NULL,
  `quotation_id` INT NOT NULL,
  PRIMARY KEY (`id`, `request_id`, `quotation_id`),
  UNIQUE INDEX `IX_U_REVIEW_id` (`id` ASC) VISIBLE,
  INDEX `IX_N_REVIEW_owner_uuid` (`owner_uuid` ASC) VISIBLE,
  INDEX `IX_N_REVIEW_forwarder_uuid` (`forwarder_uuid` ASC) VISIBLE,
  UNIQUE INDEX `IX_U_REVIEW_request_id` (`request_id` ASC) VISIBLE,
  UNIQUE INDEX `IX_U_REVIEW_quotation` (`quotation_id` ASC) VISIBLE,
  CONSTRAINT `fk_REVIEW_OWNER1`
    FOREIGN KEY (`owner_uuid`)
    REFERENCES `BAETAVERSE`.`OWNER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVIEW_FORWARDER1`
    FOREIGN KEY (`forwarder_uuid`)
    REFERENCES `BAETAVERSE`.`FORWARDER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVIEW_QUOTE_REQUEST1`
    FOREIGN KEY (`request_id`)
    REFERENCES `BAETAVERSE`.`REQUEST` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVIEW_QUOTATION1`
    FOREIGN KEY (`quotation_id`)
    REFERENCES `BAETAVERSE`.`QUOTATION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
